### ISSUE TITLE
Unauthenticated login causes error trying to retrieve repositories

### ISSUE THREAD

**Issue by joeljfischer** [octokit/octokit.objc#173]
Using the new

``` objc
[OCTUser userWithRawLogin:@"login" server:[OCTServer dotComServer]];
```

then calling

``` objc
RACSignal *request = [self.client fetchUserRepositories];
[request subscribeNext:^(OCTRepository *repository) {}]
```

to pull the repositories will cause an error at

``` objc
- [OCTClient - (RACSignal *)enqueueUserRequestWithMethod:(NSString *)method relativePath:(NSString *)relativePath parameters:(NSDictionary *)parameters resultClass:(Class)resultClass]
```

since the line

``` objc
path = [NSString stringWithFormat:@"users/%@%@", self.user.login, relativePath];
```

has `self.user.login` returning `nil`, and the `rawlogin` property contains the appropriate username.

**Comment by NashBean** [comment]
Not sure if this is related to this bug of not. But seem to me in the  OCTClient+Search.m file, braces should be added after "if (orderBy.length > 0)" to include all calls related
<code>
- (RACSignal *)searchRepositoriesWithQuery:(NSString *)query orderBy:(NSString *)orderBy ascending:(BOOL)ascending {
	NSParameterAssert(query.length > 0);
	
	NSMutableDictionary *parameters = [NSMutableDictionary dictionary];
	parameters[@"q"] = query;
	
	if (orderBy.length > 0) 
       { // <--- here
parameters[@"sort"] = orderBy;
	parameters[@"order"] = ascending ? @"asc" : @"desc";
	
	NSMutableURLRequest *request = [self requestWithMethod:@"GET" path:@"/search/repositories" parameters:parameters notMatchingEtag:nil];
	[request addValue:@"application/vnd.github.v3.text-match+json" forHTTPHeaderField:@"Accept"];
	} // <--- and here
	return [[self enqueueRequest:request resultClass:OCTRepositoriesSearchResult.class fetchAllPages:NO] oct_parsedResults];
}
<code>

**Comment by danielgalasko** [comment]
So anyone know how to actually get OctoKit to work?

**Comment by danielgalasko** [comment]
Sigh, ended up just using a token and the authenticated client vs unauthenticated one.
