### ISSUE TITLE
Question about OctoKit on iOS

### ISSUE THREAD

**Issue by wangzz** [octokit/octokit.objc#233]
I have clone OctoKit and build it success for iOS, but why the product is a framework?

![octokit](https://cloud.githubusercontent.com/assets/2884882/5797179/2e764f40-9ff0-11e4-868c-e09d05e38447.png)

What i need is a static library .a file.

**Comment by jspahrsummers** [comment]
Frameworks offer many advantages over static libraries, and are our preferred mechanism for distributing reusable code.

If you're only supporting iOS 8+, I highly recommend using the framework. If you need to support older OSes, please use [an older release](https://github.com/octokit/octokit.objc/releases/tag/0.5) of OctoKit.
