### ISSUE TITLE
I can run the app in iOS simulator, but can not run in real devices(iPhone 5s, iOS 8.1.2).

### ISSUE THREAD

**Issue by leichunfeng** [octokit/octokit.objc#234]
![1](https://cloud.githubusercontent.com/assets/5253662/5886790/0f0a5b70-a3eb-11e4-9bb8-f812ad36c13c.jpg)

**Comment by jspahrsummers** [comment]
Make sure the framework bundles are being copied into your app target. Linking them is not sufficient by itself.

**Comment by leichunfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/5253662/5894351/5035a0d2-a53f-11e4-814b-43d262be575b.png)
I've already tried what you're suggesting. Whether use the `Copy Files` phase or add the frameworks as `Embedded Binaries`, I will get the same sign code errors. Please help me to solve this problem. Thanks.
![image](https://cloud.githubusercontent.com/assets/5253662/5894384/b2567c68-a540-11e4-8762-6d91e6462b5e.png)

**Comment by jspahrsummers** [comment]
@octokit/octokit-objc @keithduncan I'm not sure what would cause this. Any ideas?

**Comment by keithduncan** [comment]
Could you paste the output of the `tree` command passing the path to the frameworks that are being signed, i.e. `/Users/leichunfeng/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Contents/Frameworks/OctoKit.framework` etc

**Comment by leichunfeng** [comment]
Of course.
CodeSign /Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework
    cd /Users/leichunfeng/workspace/github/MVVMReactiveCocoa
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Chunfeng Lei (5M34Q825AP)"

    /usr/bin/codesign --force --sign 8D1DDA94359ADA7757430B9E38E5924C5781617D --preserve-metadata=identifier,entitlements,resource-rules /Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

**Comment by keithduncan** [comment]
Sorry I specifically wanted the `tree` command output, could you run

`tree /Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework` and paste the output, this will log the framework directory structure and names of the files so I can figure out why it isn’t signing correctly.

**Comment by leichunfeng** [comment]
I'm so sorry. I also suspect that there may be some problems of the framework directory structure. The following log should be what you want.

leichunfengdeMacBook-Pro:JuJuPlus leichunfeng$ tree /Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework
/Users/leichunfeng/Library/Developer/Xcode/DerivedData/MVVMReactiveCocoa-dkjcswigkwolokaimgekabgjuzne/Build/Products/Debug-iphoneos/MVVMReactiveCocoa.app/Frameworks/OctoKit.framework
└── Versions
    └── A
        └── Modules
            └── module.modulemap

3 directories, 1 file

**Comment by leichunfeng** [comment]
This is the corresponding screenshot, may be easier to read the directory structure.
![image](https://cloud.githubusercontent.com/assets/5253662/5913079/b5cd1612-a618-11e4-9c91-34359ee5065c.png)

**Comment by jspahrsummers** [comment]
That definitely looks invalid. How are you building OctoKit?

**Comment by leichunfeng** [comment]
In fact, I'm not sure how to build the OctoKit framework correctly. I just select the `OctoKit iOS` scheme, and use the `Command+B` shortcut to build it. Is it right? Please tell me the steps to build the OctoKit framework correctly in detail.

**Comment by jspahrsummers** [comment]
Follow [OS X installation steps 3 and 4](https://github.com/octokit/octokit.objc#importing-octokit). The instructions for iOS are out of date. :confused:

**Comment by leichunfeng** [comment]
That is actually what I did and it resulting the above sign errors as you can see. Is there any other way I can try it?

**Comment by jspahrsummers** [comment]
I dunno, I haven't seen this before. @keithduncan, any other ideas?

**Comment by keithduncan** [comment]
Sorry I haven’t seen this and don’t have time to debug further

**Comment by leichunfeng** [comment]
I am so excited that I have solved this problem and I can run the app in real devices now. I happened to see this solution in the `README.md` of [facebook/pop](https://github.com/facebook/pop) repository.
![image](https://cloud.githubusercontent.com/assets/5253662/6019697/752a537e-abde-11e4-98d9-a575ae325f36.png)

**Comment by robrix** [comment]
Well, good to know! Thanks for reporting the solution :smile:
