### ISSUE TITLE
outdated/unclear installation instructions

### ISSUE THREAD

**Issue by morganchen12** [octokit/octokit.objc#239]
The second installation step (run `script/bootstrap`) always fails with this cryptic error:

    *** Checking dependencies...
    fatal: Not a git repository (or any of the parent directories): .git
    logout

    [Process completed]

However, I was able to build OctoKit for iOS using Carthage. Here's my Cartfile:

    github "octokit/octokit.objc"

Here's the output from running `carthage update --use-submodules`:

    Morgans-MacBook-Air:OctoKitTest morganchen$ carthage update --use-submodules
    *** Fetching octokit.objc
    *** Fetching Mantle
    *** Fetching ReactiveCocoa
    *** Checking out Mantle at "1.5.4"
    *** Checking out octokit.objc at "0.7.4"
    *** Checking out ReactiveCocoa at "v2.4.6"
    *** xcodebuild output can be found in /var/folders/kb/m3fsh6754lq18xbtn5d8wjzc0000gn/T/carthage-xcodebuild.kjE0GS.log
    *** Building scheme "Mantle iOS" in Mantle.xcworkspace
    *** Building scheme "Mantle Mac" in Mantle.xcworkspace
    *** Building scheme "ReactiveCocoa iOS" in ReactiveCocoa.xcworkspace
    *** Building scheme "ReactiveCocoa Mac" in ReactiveCocoa.xcworkspace
    *** Building scheme "AFNetworking iOS" in OctoKit.xcworkspace
    *** Building scheme "AFNetworking Mac" in OctoKit.xcworkspace
    *** Building scheme "ISO8601DateFormatter iOS" in OctoKit.xcworkspace
    *** Building scheme "ISO8601DateFormatter Mac" in OctoKit.xcworkspace
    *** Building scheme "OctoKit iOS" in OctoKit.xcworkspace
    *** Building scheme "OctoKit Mac" in OctoKit.xcworkspace
    ** BUILD FAILED **

    The following build commands failed:
      CompileC /Users/morganchen/Library/Developer/Xcode/DerivedData/OctoKit-altssbakrrgakpdczigiwanxrkkf/Build/Intermediates/ReactiveCocoa.build/Release/ReactiveCocoa-iOS.build/Objects-normal/x86_64/UIControl+RACSignalSupport.o ReactiveCocoa/UIControl+RACSignalSupport.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
      CompileC /Users/morganchen/Library/Developer/Xcode/DerivedData/OctoKit-altssbakrrgakpdczigiwanxrkkf/Build/Intermediates/ReactiveCocoa.build/Release/ReactiveCocoa-iOS.build/Objects-normal/x86_64/UITextView+RACSignalSupport.o ReactiveCocoa/UITextView+RACSignalSupport.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (2 failures)

And the custom run script from Carthage:

![screen shot 2015-02-13 at 11 00 38 am](https://cloud.githubusercontent.com/assets/4529021/6193387/aa5559e8-b36f-11e4-89ea-42ee81d253b1.png)

The error building OctoKit Mac leads me to believe the installation instructions won't be as simple for OS X development, but as it stands right now the instructions are fairly cryptic and had me nuking my project on more than one occasion.

**Comment by jspahrsummers** [comment]
`script/bootstrap` expects to be run from within a Git repository. If you don't have that (e.g., you downloaded a zip instead of cloning the OctoKit repository), it will fail.

Carthage should work for both iOS and OS X builds. Can you share the `xcodebuild` log file?

**Comment by morganchen12** [comment]
Creating a new Xcode project, initializing a git repo, adding octokit.objc as a submodule per the instructions, and then running `script/bootstrap` fails with the same error.

    /Users/morganchen/dev/iOS/BootstrapTest/octokit.objc/script/bootstrap ; exit;
    Morgans-MacBook-Air:~ morganchen$ /Users/morganchen/dev/iOS/BootstrapTest/octokit.objc/script/bootstrap ; exit;
    *** Checking dependencies...
    fatal: Not a git repository (or any of the parent directories): .git
    logout

    [Process completed]

[Here's the repository for reference.](https://github.com/morganchen12/BootstrapTest)

[Here's the build log as a gist.](https://gist.github.com/morganchen12/b7c3fbd27cc3a56d2851). If you have errors viewing it I can upload it elsewhere.

**Comment by jspahrsummers** [comment]
> Creating a new Xcode project, initializing a git repo, adding octokit.objc as a submodule per the instructions, and then running `script/bootstrap` fails with the same error.

Sorry, it's not documented, but `script/bootstrap` needs to run within the working directory of the OctoKit repository.

> Here's the build log as a gist.

The error appears to be:

```
In file included from /Users/morganchen/dev/iOS/OctoKitTest/Carthage/Checkouts/octokit.objc/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/UIControl+RACSignalSupport.m:9:
/Users/morganchen/dev/iOS/OctoKitTest/Carthage/Checkouts/octokit.objc/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/UIControl+RACSignalSupport.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
        ^
1 error generated.
```

… which doesn't make any sense to me. Which version of Xcode are you using?

**Comment by morganchen12** [comment]
Moving `script/bootstrap` out of the `script/` folder and into the root octokit directory (octokit.objc) fails with the same error message. Moving either the `bootstrap` file individually or the entire `script` folder into the root of my project or the root folder of the OctoKit submodule also fails with the same error.

`xcodebuild` is using Xcode 6.1.1, but I also have Xcode 6.3 beta installed.

    Morgans-MacBook-Air:~ morganchen$ xcode-select -print-path
    /Applications/Xcode.app/Contents/Developer
    Morgans-MacBook-Air:~ morganchen$ xcodebuild -version
    Xcode 6.1.1
    Build version 6A2008a

Regardless, it doesn't make sense to me either that any version of Xcode should fail when importing UIKit either.

**Comment by morganchen12** [comment]
Is there anything wrong with importing UIKit in the OctoKit Mac build scheme?

**Comment by mdiep** [comment]
> Is there anything wrong with importing UIKit in the OctoKit Mac build scheme?

Yes, there is.

1. UIKit doesn't exist on the Mac.
2. OctoKit shouldn't import or have a dependency on a UI framework on either platform
