### ISSUE TITLE
How to get user login to fetchUserEvents with?

### ISSUE THREAD

**Issue by cesteban** [octokit/octokit.objc#241]
I'm doing native authentication, and signing in with:

```objective-c
OCTUser *user = [OCTUser userWithRawLogin:username server:OCTServer.dotComServer];
[[OCTClient signInAsUser:user password:password oneTimePassword:nil scopes:(OCTClientAuthorizationScopesUser|OCTClientAuthorizationScopesRepository) note:nil noteURL:nil fingerprint:nil]
  subscribeNext:^(OCTClient *authenticatedClient) {
     // do stuff with the authenticatedClient
  }];
```

This works perfect, and I use the authenticatedClient to fetch repos list, user info, and more. However, when I try to fetchUserNotifications:

```objective-c
[[self.authenticatedClient fetchUserEventsNotMatchingEtag:nil]
  subscribeNext:^(OCTEvent *event) {
     // do stuff with the event
  } error:^(NSError *error) {
     // handle error
  }];
```

I got a 404 error. The reason is that the ```fetchUserNotifications``` method in ```OCTClient+Events``` is composing the path of the request with ```self.user.login```, which is nil, so the path look like this: ```users/(null)/received_events```

As far as I know, the only way to fill the ```login``` property of ```OCTUser``` is through ```fetchUserInfo``` method of ```OCTClient```. However, in order to obtain an valid ```OCTClient``` I need to authenticate with an ```OCTUser```, so that cannot be the correct way of doing this.

I must be missing something really obvious here. Any help would be very much appreciated.

Thanks in advance!

**Comment by cesteban** [comment]
I understand this is related to #173

**Comment by cesteban** [comment]
Just falling back to ```self.user.rawLogin``` when ```self.user.login == nil``` works for my use case, but I ignore how this could affect Enterprise users with LDAP authentication.

I'll stick to this temporary fix for the moment:

https://github.com/cesteban/octokit.objc/commit/c74d74136b93c4e7f89a22ac6d58044b4726ba4b

Hope it helps.

**Comment by joshaber** [comment]
Indeed, it does look like another manifestation of #173 so I'm going to go ahead and close this out.

We'd welcome a PR that fixes this!
