### ISSUE TITLE
Bridging header with swift

### ISSUE THREAD

**Issue by datomnurdin** [octokit/octokit.objc#242]
Is it possible to do bridging header with this plugin? Thanks

**Comment by joshaber** [comment]
I thought Xcode would automatically provide one for frameworks?

**Comment by datomnurdin** [comment]
What do you mean provide one for frameworks?

**Comment by joshaber** [comment]
What exactly are you trying to do?

**Comment by datomnurdin** [comment]
Because my project using swift. I need to do bridging header.

**Comment by mdiep** [comment]
You should be able to import octokit in your project's bridging header.
