### ISSUE TITLE
Unable to install octokit via cocoapod

### ISSUE THREAD

**Issue by datomnurdin** [octokit/octokit.objc#243]
I'm unable to install octokit via cocoapod.

`[!] Unable to satisfy the following requirements:

- `ReactiveCocoa (~> 2.4)` required by `Podfile`
- `ReactiveCocoa (~> 2.4)` required by `Podfile`
- `ReactiveCocoa (~> 2.4)` required by `Podfile`
- `ReactiveCocoa (= 2.4.7)` required by `Podfile.lock`
- `ReactiveCocoa (~> 2.2.2)` required by `OctoKit (0.5)``

**Comment by joshaber** [comment]
We don't use CocoaPods and consequently don't maintain the podspec. You'll want to check whatever CocoaPods resources there are.
