### ISSUE TITLE
Getting private Issues

### ISSUE THREAD

**Issue by RuiAAPeres** [octokit/octokit.objc#248]
Using the following:

```objc
OCTClient *client = [RPSessionManager sharedManager].client;
    
 NSURLComponents *components = [[NSURLComponents alloc] initWithURL:self.notification.latestCommentURL resolvingAgainstBaseURL:YES];
 [components setHost:client.baseURL.absoluteString];
[client getPath:components.path parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {

}];
```
For private repos, will return me a 404.  I request authorization like this:

```
OCTUser *user = [OCTUser userWithRawLogin:self.username server:OCTServer.dotComServer];
return [OCTClient signInAsUser:user password:self.password oneTimePassword:self.authenticationCode scopes:OCTClientAuthorizationScopesNotifications | OCTClientAuthorizationScopesRepository];
```

For public repos,  it will work as expected. The case that it's failing is:

> https://api.github.com/repos/RuiAAPeres/Octify/issues/comments/77664771

I think it follows the expected format. **It was also reported, that users that have access to the private repo are able to get the issue, but I can't.** (I am the owner of the repo). For example:

* I create an issue. User A is able to see the issue.
* User A creates an issue. I am unable to see it.

**Comment by RuiAAPeres** [comment]
Was able to solve it, by creating a new application on Github. :/

**Comment by jspahrsummers** [comment]
Ah, that probably means your token had a set of old scopes. Revoking it might've worked also.

**Comment by RuiAAPeres** [comment]
@jspahrsummers are the scopes per use or per token?

**Comment by jspahrsummers** [comment]
Per token.
