### ISSUE TITLE
Notifications fetch limit

### ISSUE THREAD

**Issue by RuiAAPeres** [octokit/octokit.objc#252]
I am currently seeing that calling 

```
- (RACSignal *)fetchNotificationsNotMatchingEtag:(NSString *)etag includeReadNotifications:(BOOL)includeRead updatedSince:(NSDate *)since;
```
Will return me at most 50 results. Is there a way to better control this? Changing limit, pagination?

**Comment by jspahrsummers** [comment]
Do you get the same results when using `curl`?

**Comment by RuiAAPeres** [comment]
I haven't tried with `curl`. I wanted to make sure your abstraction could solve this. There have been cases where I had more than 50 notifications, I could see them at https://github.com/notifications?all=1, but the method would only return me 50.

**Comment by jspahrsummers** [comment]
Without a comparative example from `curl`, we can't know whether this is a GitHub API bug or an OctoKit bug. :wink:

**Comment by RuiAAPeres** [comment]
It's an API limitation (curl only gets 50), although the website is able to display +50.

**Comment by jspahrsummers** [comment]
Hmm, if you use `curl -v` (to log headers), do you see any `Link` headers sent from the API? If so, could you please copy and paste it here?

**Comment by RuiAAPeres** [comment]
I am using Postman chrome plugin

```
Access-Control-Allow-Credentials → true
Access-Control-Allow-Origin → *
Access-Control-Expose-Headers → ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control → private, max-age=60, s-maxage=60
Content-Encoding → gzip
Content-Security-Policy → default-src 'none'
Content-Type → application/json; charset=utf-8
Date → Mon, 09 Mar 2015 17:20:39 GMT
Last-Modified → Mon, 09 Mar 2015 17:20:07 GMT
Server → GitHub.com
Status → 200 OK
Strict-Transport-Security → max-age=31536000; includeSubdomains; preload
Transfer-Encoding → chunked
Vary → Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding
X-Content-Type-Options → nosniff
X-Frame-Options → deny
X-GitHub-Media-Type → github.v3
X-GitHub-Request-Id → 6D4817C8:1485:CC929E:54FDD667
X-Poll-Interval → 60
X-RateLimit-Limit → 5000
X-RateLimit-Remaining → 4994
X-RateLimit-Reset → 1425921700
X-Served-By → a241e1a8264a6ace03db946c85b92db3
X-XSS-Protection → 1; mode=block
```

**Comment by jspahrsummers** [comment]
Thanks for grabbing that! I've filed an issue with the API team about the missing `Link` header.

It looks like—although I haven't tried myself—that `?page=2`, `?page=3`, etc. might allow you to paginate manually, if you're okay creating your own requests.

Until the `Link` header gets fixed, though, OctoKit won't be able to paginate it automatically.

**Comment by RuiAAPeres** [comment]
@jspahrsummers is there an issue I can follow for this?

**Comment by jspahrsummers** [comment]
No, sorry, we don't have a public tracker for API issues.

**Comment by gjtorikian** [comment]
@RuiAAPeres This has been fixed as of a couple of weeks ago.

**Comment by RuiAAPeres** [comment]
Thanks @gjtorikian !
