### ISSUE TITLE
Create Gist API Issue

### ISSUE THREAD

**Issue by JeremyAgost** [octokit/octokit.objc#254]
I've been using the framework to create gists programmatically and recently, the API stopped working. It suddenly started to return 422 status code, indicating improper content. Here's a sample of the JSON being POST'd by OctoKit.
```
{"public":0,"files":{"Summary":{"content":"Summary Content"},"TestFile":{"content":"Foo Content"}},"description":"The Description"}
```
It looks like the "public" value is being sent as an integer. When I change it to a boolean, the request is parsed correctly. I'm not really sure how to fix the schema encoding, I'm not familiar with the JSON framework that this project uses.

This is my hacky fix. (OCTClient+Gists.m)
```objc
- (RACSignal *)createGistWithEdit:(OCTGistEdit *)edit {
	NSParameterAssert(edit != nil);

	if (!self.authenticated) return [RACSignal error:self.class.authenticationRequiredError];

	NSDictionary *parameters = [MTLJSONAdapter JSONDictionaryFromModel:edit];
	
	// Convert integer true/false to boolean
	NSMutableDictionary * parametersM = [parameters mutableCopy];
	id public = parametersM[@"public"];
	if ([public isKindOfClass:[NSNumber class]]) {
		parametersM[@"public"] = [public boolValue] ? @(YES) : @(NO);
	}
	parameters = parametersM;
	
	NSURLRequest *request = [self requestWithMethod:@"POST" path:@"gists" parameters:parameters notMatchingEtag:nil];
	return [[self enqueueRequest:request resultClass:OCTGist.class] oct_parsedResults];
}
```

**Comment by jspahrsummers** [comment]
Thanks for catching that!

If using `@YES` and `@NO` fixes the issue, I think we should be using Mantle's [`MTLBooleanValueTransformerName`](https://github.com/Mantle/Mantle/blob/a4a26feb8f90c3a60241ea344839e1cbb2901adf/Mantle/NSValueTransformer%2BMTLPredefinedTransformerAdditions.h#L21) inside `OCTGistEdit`.

If you're interested in submitting that fix, could you please open a pull request? :pray:
