### ISSUE TITLE
Octokit as a public Framework

### ISSUE THREAD

**Issue by andrewjburnett** [octokit/octokit.objc#257]
This type of question may be better suited for a platform like Stackoverflow, but since it pertains to Octokit I figured I would get the most insightful response by asking it here.

I understand the majority of the implementation details surrounding Octokit. Given that it was built with the intent of being used in other iOS applications - in order to allow them access to Github's API - it makes sense that Octokit requires an OCTClient instance to be initialized prior to being used. However, if one is building a "internal" networking layer to communicate with a REST api, would this practice still be advisable. Alternatively, would it make more sense to create some sort of "sharedClient" object (singleton) that is used throughout the application and can be called on the class when needed?

For companies that don't open source ALL of their code but do create a public API, is it common practice for them to build their networking layers (the one they use internally and one that is made for public use) with similar design decisions. Is there typically overlap between these code bases?

**Comment by joshaber** [comment]
>For companies that don't open source ALL of their code but do create a public API, is it common practice for them to build their networking layers with similar design decisions.

One of the great things about open sourcing the components involved in your app is that it forces loose coupling. Regardless of whether you plan to open source your network layer, designing it in such a way that it isn't tightly coupled with the rest of your app is a fantastic goal.

Shared instances are (usually) a bad choice for all the usual reasons that singletons are a bad choice.

I can't really speak to whether this sort of design is _common_, but I hope most places would endorse those values :smile:

**Comment by andrewjburnett** [comment]
Thanks Josh! I appreciate the feedback.
