### ISSUE TITLE
Trouble when getting repositories for an authenticated user

### ISSUE THREAD

**Issue by Vamston** [octokit/octokit.objc#259]
After I authenticated a user via OAuth, I tried to get the user's repo, but only public repos are returned from the server. How can I get the user's private repo?

**Comment by joshaber** [comment]
It's hard to say without seeing any code. On its face that sounds right.

**Comment by Vamston** [comment]
[[OCTClient signInAsUser:userForRawLogin password:@"passowrd" oneTimePassword:nil scopes:OCTClientAuthorizationScopesRepository]
    subscribeNext:^(id x) {
        OCTClient *client = (OCTClient *)x;
        [[client fetchUserRepositories]
        subscribeNext:^(id x) {

        } error:^(NSError *error) {
            
        } completed:^{
            
        }];
    } error:^(NSError *error) {
        
    } completed:^{
        
    }];

I used this code to fetch my repos, I have no public repo but 5 private repos and nothing gets returned from the subscribeNext block.
So what u mean is that there is no way to fetch private repos?

**Comment by Vamston** [comment]
I looked at the data returned from the server, when I am authenticating using the Repositories scope, the parameters got send are:
{
    "client_secret" = 6aab019ce21fa2a627c110bb49f6f5b17b4bb951;
    scopes =     (
        repo
    );
}

and the response parameters are:
{
    app =     {
        "client_id" = e310071d66644d1d4f47;
        name = OctoHand;
        url = "http://www.vamston.com/octohand/";
    };
    "created_at" = "2015-03-31T12:30:19Z";
    id = 16647175;
    note = "<null>";
    "note_url" = "<null>";
    scopes =     (
        user
    );
    token = b0b92d5d0a747134b1c7ea517871b44e4670921b;
    "updated_at" = "2015-03-31T12:30:19Z";
    url = "https://api.github.com/authorizations/16647175";
}

why the scopes array in the response parameters doesn't include the "repo"? Or is there anything that I did is wrong?

**Comment by joshaber** [comment]
I don't see anything obviously wrong with that code. You might check out #183 since it sounds similar.

**Comment by Vamston** [comment]
I saw #183 two days ago but nothing's changed after I did everything the esttorhe did.

**Comment by jspahrsummers** [comment]
@Vamston You were probably testing with a different set of scopes before. Can you try revoking your current authorization and creating a new one with the correct scopes?

**Comment by Vamston** [comment]
@jspahrsummers After I revoked all user tokens, all the authentication request made to the GitHub server keep returning me empty tokens, but with an additional "token_last_eight" in the response parameters, what does this mean?

**Comment by Vamston** [comment]
@jspahrsummers I

**Comment by Vamston** [comment]
@jspahrsummers Sorry for accidentally close this issue...
After I read the changes made to the Authorizations API, I figured out how the "token_last_eight" works, but the GitHub server still doesn't return me the private repos after I revoked all user tokens...

**Comment by jspahrsummers** [comment]
Just to clarify, you've received a new token after revocation, and that new token still isn't giving you private repositories?

**Comment by Vamston** [comment]
@jspahrsummers After I double checked my code, I found that before requesting the repo scope, I made a request using the user scope to check weather the username and password the user entered is correct. If I remove the code using the user scope and only make request use the repo scope, the private repositories are returned.

So I should use different OCTClient instances for different scopes?

**Comment by jspahrsummers** [comment]
@Vamston You should request all the scopes you'll (ever) need at the same time. A token's scopes can't be changed later with the current implementation.

**Comment by Vamston** [comment]
Thank @jspahrsummers  for clarify the authentication flow for me.

**Comment by jspahrsummers** [comment]
No problem!
