### ISSUE TITLE
Any suggestions for sharing token between different devices?

### ISSUE THREAD

**Issue by Vamston** [octokit/octokit.objc#261]
Since the token attribute is deprecated in the new [Authorizations API](http://developer.github.com/changes/2014-12-08-removing-authorizations-token/). Are there any suggestions for sharing token between different devices? 
Say if a user is authenticated on the iPhone and wants to switch to his/her iPad to use the iPad version of the app.

**Comment by joshaber** [comment]
Ideally you really shouldn't. Tokens should be per-device.

**Comment by Vamston** [comment]
@joshaber Then what should I do if the user is already authenticated on one device and switched to another device, but on that device after the user send an authentication request the server is only gonna return the "token_last_eight" and the "hashed_token" but not the token itself?

**Comment by joshaber** [comment]
You should use the `fingerprint` to distinguish between the devices. See https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint.

**Comment by Vamston** [comment]
My app can use difference tokens on different devices! Thx @joshaber!
