### ISSUE TITLE
Is there a way to retrieve the trending repositories?

### ISSUE THREAD

**Issue by leichunfeng** [octokit/octokit.objc#264]
Is there a way to retrieve the trending repositories or any GitHub API can help us to implement the feature much like GitHub Explore?

**Comment by joshaber** [comment]
Just quickly looking at https://developer.github.com/v3/ I don't see any APIs like that. You might be able to recreate something using search, maybe?

I'd recommend you email support@github.com so they can pass on your request to the API team.
