### ISSUE TITLE
Using signInToServerUsingWebBrowser: with Swift

### ISSUE THREAD

**Issue by istx25** [octokit/octokit.objc#265]
Hello, everyone!

I am trying to utilise the `signInToServerUsingWebBrowser:` API in Swift, but for some reason I can not invoke the `subscribeNext:` part of the method call. 

I am looking for the Swift equivalent of:
```objectivec
[[OCTClient
    signInToServerUsingWebBrowser:OCTServer.dotComServer scopes:OCTClientAuthorizationScopesUser]
    subscribeNext:^(OCTClient *authenticatedClient) {
        // Authentication was successful. Do something with the created client.
    } error:^(NSError *error) {
        // Authentication failed.
    }];
```

My attempt:
```swift
OCTClient.signInToServerUsingWebBrowser(OCTServer.dotComServer(), scopes: OCTClientAuthorizationScopes(), subscribeNext: { (authenticatedClient: OCTClient, error: NSError) -> Void in
    // Implementation goes in here.
})
```

I receive an "*Extra argument 'subscribeNext' in call.*" error. ([Image](https://cloud.githubusercontent.com/assets/6799989/8022903/9e81d824-0ca4-11e5-8d9f-8393a227b216.png))

What am I missing? :confused:

**Comment by CodaFi** [comment]
The syntax of your translation is not quite right

```swift
OCTClient.signInToServerUsingWebBrowser(OCTServer.dotComServer(), scopes: OCTClientAuthorizationScopes()).subscribeNext({ (x : AnyObject!) -> Void in
    // Implementation goes in here.
}, error: { (error : NSError!) -> Void in
  // Catch errors here.
})
```

**Comment by istx25** [comment]
Welp. Thanks @CodaFi.

I was just going through [yeahdongcn/GCompare @ Core.swift](https://github.com/yeahdongcn/GCompare/blob/master/GCompare/Core.swift) and found the same thing. 

Definitely an "oooooooohhhhhhhhhhh" moment. I should probably make another :coffee:.
