### ISSUE TITLE
Does OctoKit have anything like Parse's PFUser.currentUser()?

### ISSUE THREAD

**Issue by istx25** [octokit/octokit.objc#266]
Does OctoKit have anything like Parse's `PFUser.currentUser()` API? 
I am looking for an equivalent to [this](https://parse.com/docs/osx/api/Classes/PFUser.html#//api/name/currentUser).

Similar Example:
```swift
if nil == PFUser.currentUser() {
   // No user.
   presentLoginViewController()
} else {
   // There is a user.
   println("success")
}
```

Any ideas?

>PS: If this doesn't exist, I'd love to help bring it to life, as it would be a very useful feature for this library.

**Comment by mdiep** [comment]
`OCTClient` has an `isAuthenticated` method as well as a method to get the current user. There's no global method because OctoKit supports multiple clients.

**Comment by istx25** [comment]
Thank you for your reply, @mdiep!

**Comment by istx25** [comment]
https://github.com/octokit/octokit.objc/issues/268
