### ISSUE TITLE
Question about the .subscribeNext closure!

### ISSUE THREAD

**Issue by istx25** [octokit/octokit.objc#268]
May I first apologise for the abundance of issue reports I'm filing, but I noticed that the `.subscribeNext` closure (in the example below) is not being ran and I have no idea why.

```swift
OCTClient.signInToServerUsingWebBrowser(OCTServer.dotComServer(), scopes: .User).subscribeNext({ (authenticatedClient: AnyObject!) -> Void in
   // Success
   println("success")
}, error: { (error: NSError!) -> Void in
   println("something went wrong")
})
```

The application opens up the web-authentication in Safari, but I never see the "success" `println()`. For an example of this issue in action, checkout "[istx25/pistachio @ OnboardingViewController.swift](https://github.com/istx25/pistachio/blob/master/Pistachio/Controllers/OnboardingViewController.swift)".

Any ideas?

:confused:

**Comment by joshaber** [comment]
Does your `AppDelegate.application(openURL:sourceApplication:annotation:)` func get called?

**Comment by istx25** [comment]
@joshaber Yes.

```swift
func application(application: UIApplication, s url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool {
   if url.host == "oauth" {
      OCTClient.completeSignInWithCallbackURL(url)
      return true
   } else {
      return false
   }
}
```

**Comment by istx25** [comment]
The breakpoint pauses on `if url.host == "oauth" {`

**Comment by joshaber** [comment]
Does it then call `OCTClient.completeSignInWithCallbackURL`?

**Comment by istx25** [comment]
:confused: Nope.

**Comment by istx25** [comment]
Just noticed that.

**Comment by istx25** [comment]
Do you have any idea why?

**Comment by joshaber** [comment]
What's `url.host`?

**Comment by istx25** [comment]
@joshaber: It's from [this example](https://github.com/octokit/octokit.objc#signing-in-through-a-browser).

```objectivec
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)URL sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    // For handling a callback URL like my-app://oauth
    if ([URL.host isEqual:@"oauth"]) {
        [OCTClient completeSignInWithCallbackURL:URL];
        return YES;
    } else {
        return NO;
    }
}
```

**Comment by mdiep** [comment]
He's asking what the value of `url.host` is when your breakpoint pauses.

**Comment by istx25** [comment]
Oh sorry, my bad. I think this is what you're asking for: :confused:

![screen shot 2015-06-10 at 2 44 04 pm](https://cloud.githubusercontent.com/assets/6799989/8094963/36239dd4-0f7f-11e5-95b5-5b3d438d0b61.png)

**Comment by istx25** [comment]
Figured out why it wasn't working. I set my **Authorization callback URL** to `pistachio-app://foo` when it should have been `pistachio-app://oauth`.

**Comment by istx25** [comment]
Thanks for you time, @joshaber and @mdiep! :smile:
