### ISSUE TITLE
Support for the Releases API

### ISSUE THREAD

**Issue by deepakprabhakara** [octokit/octokit.objc#269]
If I am not totally mistaken there is currently no support for the Releases API yet (https://developer.github.com/v3/repos/releases).

Is there a plan to add this in the near future?

Thanks.
Deepak.

**Comment by mdiep** [comment]
New APIs are usually added as people need them. Pull requests are welcome. :smile:

**Comment by deepakprabhakara** [comment]
I hope to get around to it then. :)
