### ISSUE TITLE
How do we sign users out of OctoKit?

### ISSUE THREAD

**Issue by istx25** [octokit/octokit.objc#271]
I am having a hard time finding a solution to this problem. I am looking for an OctoKit function that terminates the client session. (with a success/error closure because I need to send the user back to the login page)

![image](https://cloud.githubusercontent.com/assets/6799989/8872102/2c315d6c-31f2-11e5-8f48-79f29ac78bf2.png)

Does OctoKit have anything? :innocent:

**Comment by a2** [comment]
http://loginisnotaverb.com :heart:

**Comment by joshaber** [comment]
Octokit doesn't have a session to terminate. Authentication is done using a username + token. Logging out is just a matter of the app not using or deleting the stored token.

**Comment by istx25** [comment]
@joshaber Oh okay. How would one delete the stored token?

**Comment by joshaber** [comment]
Hopefully you're storing it in the Keychain, so you'd need to consult those APIs.

**Comment by akring** [comment]
Hi there,I meet the same situation now.My problem is,when I delete my stored token in keychain and try to `signInToServerUsingWebBrowser:` in Safari,I will sign in with the former user automatically.Is anything else I should do for this?
