### ISSUE TITLE
Get User feed, and ETAG

### ISSUE THREAD

**Issue by remirobert** [octokit/octokit.objc#273]
Hello

- Is it possible to get the user main feed. To see all the activity concerning my repository, and the user i am following ?

- And second question where can i get the ETAG ? For some request i need it (fetchUserEvents), and it's not explain at all in the readme. I saw, that it's present in the OCTResponse object.

```Objective-c
[[[GithubUser sharedInstace].client fetchUserEventsNotMatchingEtag:nil] subscribeNext:^(id x) {
                
 } error:^(NSError *error) {
 }];
```

Thanks in advance for your help.

**Comment by joshaber** [comment]
>Is it possible to get the user main feed.

I'd think that'd be `-fetchUserEventsNotMatchingEtag:` that you cite. Is that not it?

>And second question where can i get the ETAG ?

All API calls send `OCTResponse` objects, which has an `etag` property. You'd use it something like this:

```objc
[[[GithubUser sharedInstace].client fetchUserEventsNotMatchingEtag:nil] subscribeNext:^(OCTResponse *response) {
  NSString *etag = response.etag;
  OCTEvent *event = response.parsedResult;
  // do stuff
 } error:^(NSError *error) {
 }];
```

**Comment by joshaber** [comment]
Closing.

**Comment by shenAlexy** [comment]
@joshaber I also use your advice, like this:
`OCTUser *user = [OCTUser userWithRawLogin:SSKeychain.rawLogin server:OCTServer.dotComServer];
    OCTClient *client = [OCTClient authenticatedClientWithUser:user token:SSKeychain.token];
    
    [[client fetchUserEventsNotMatchingEtag:nil] subscribeNext:^(OCTResponse *response) {
        NSString *etag = response.etag;
        
        [[UserDefaultTool shareInstance] setETag:etag];
        
    } error:^(NSError *error) {
        DLog(@"error:%@",error.description);
    }];`

but I found response.etag is nil, Why?
