### ISSUE TITLE
Missing Attributes e.G. in gists

### ISSUE THREAD

**Issue by paxos** [octokit/octokit.objc#274]
I noticed that most of the attributes that the API returns are ignored as the model does not have matching attributes for it. Why is that?

So I just wonder: What is the suggest approach to work with this framework?
Fork and add required attributes to the model itself?

**Comment by joshaber** [comment]
>Why is that?

Generally features, attributes, etc. are added on an as-needed basis.

>Fork and add required attributes to the model itself?

Sure! And then open a PR here so we can incorporate them too :smile:

**Comment by paxos** [comment]
Will do, thanks :)
