### ISSUE TITLE
OctoKit on Cocoapods is broken.

### ISSUE THREAD

**Issue by wmcbain** [octokit/octokit.objc#277]
#### Couple of Things

- Currently on [CocoaPods](https://cocoapods.org/?q=octokit) the latest release is set to 0.5. Might be time to bump this as the current release is 0.7.6.
- Linking from Cocoapods in a Podfile is currently broken.

#### Errors

- Referencing OctoKit in a Podfile with `pod 'OctoKit', '0.5'` results in:
```
[!] Unable to satisfy the following requirements:`

- `ISO8601DateFormatter (~> 0.7.0)` required by `OctoKit (0.5)`
```

#### Resolution

To resolve I created a custom podspec:

```
Pod::Spec.new do |s|
  s.name          = 'OctoKit'
  s.version       = '0.7.6'
  s.source        = { :git => 'https://github.com/octokit/octokit.objc.git', :commit => '1a6667f'}
  s.source_files  = 'OctoKit/*.{h,m}'
  s.requires_arc  = true
end
```

Just wanted to bring this to your attention and hopefully get that version bumped on Cocoapods. :+1:

**Comment by mdiep** [comment]
I'm not sure who maintains the podspec or if they watch this repository.

**Comment by joshaber** [comment]
Indeed, since we don't maintain the podspec I'll go ahead and close this. But it'd be awesome if you could open a PR on CocoaPod's Specs repo. :metal:

**Comment by jeroenransijn** [comment]
Even though this is closed, would greatly appreciate it to get an update when the cocoapod is updated.
