### ISSUE TITLE
How to use from Swift?

### ISSUE THREAD

**Issue by dogweather** [octokit/octokit.objc#285]
I'd really like to see docs or examples of how to use this while programming in Swift, assuming it's possible.

**Comment by joshaber** [comment]
Indeed, you can use any Objective-C code from Swift :smile: Check out https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html.

Let us know if you run into any octokit-specific problems!

**Comment by onmyway133** [comment]
FYI, I'm porting this to Swift https://github.com/onmyway133/Github.swift, using RxSwift

**Comment by mdiep** [comment]
I also started a Swift library recently: https://github.com/mdiep/Tentacle. It uses ReactiveCocoa.
