### ISSUE TITLE
How to fetch the trending data?

### ISSUE THREAD

**Issue by allsome** [octokit/octokit.objc#287]
GitHub trending is one of most attractive parts.however,I find all kinds of data interfaces but the trending.
Please let me know  whether the KEY data interface is provided.If not ,I will be very grateful if telling me how to fetch them.Thank you and wish you well with your work.
![issue](https://cloud.githubusercontent.com/assets/5960733/11324500/82d2029e-916e-11e5-8dcb-dd8904255eee.png)

**Comment by joshaber** [comment]
No, I don't believe there's an API for that. https://developer.github.com would be the right place to check.

**Comment by allsome** [comment]
But,I find a [Ruby repo](https://github.com/rochefort/git-trend) achieve it.

**Comment by joshaber** [comment]
Yup, looks like they're scraping the website to get that data.
