### ISSUE TITLE
Setting the redirect uri with signInToServerUsingWebBrowser

### ISSUE THREAD

**Issue by jeroenransijn** [octokit/octokit.objc#288]
I have a GitHub OAuth application setup with a callback that goes back to my Firebase application for my web interface. I also want to be able to login with their accounts on your phone, so you're logged in on both devices at the same time.

In the [OAuth docs](https://developer.github.com/v3/oauth/#redirect-urls) there is a notice of sending a `redirect_uri` if you wan't to overwrite the callback. I can't find how this is done using OctoKit since `OCTClient.signInToServerUsingWebBrowser` only takes two arguments, and I can't find a setter or documentation on this.

Is what I am doing possible at all? Or is the only way to implement my custom login the app (which is something I implemented, but thought the browser interface is more reassuring for users)?

**Comment by joshaber** [comment]
Indeed, currently octokit.objc doesn't support that. We'd recommend just setting the callback URL in the OAuth app settings.

**Comment by jeroenransijn** [comment]
The problem however is that I have to set my callback to the Firebase web app, and not the mobile client.  Will have to implement a custom interface.

**Comment by mdiep** [comment]
It seems that the GitHub API doesn't allow you to specify a wholly different redirect URL: https://developer.github.com/v3/oauth/#redirect-urls.
