### ISSUE TITLE
How to logout if I used web browser sign in?

### ISSUE THREAD

**Issue by akring** [octokit/octokit.objc#290]
I used:
```
[OCTClient signInToServerUsingWebBrowser:OCTServer.dotComServer scopes:OCTClientAuthorizationScopesUser]
```
 for users to sign their Github account in by web browser.

The problem is how can I log them out?I removed token and other things I stored in my app,and I recalled
 ```
[OCTClient signInToServerUsingWebBrowser:OCTServer.dotComServer scopes:OCTClientAuthorizationScopesUser]
```
the browser opened and login the former user automatically.

I'm totally lost:(

**Comment by joshaber** [comment]
Correct, there's no way to do this. The user would need to log themselves out using the browser.

**Comment by verma-manish58** [comment]
test comment

**Comment by jastp** [comment]
comment from iOS

**Comment by verma-manish58** [comment]
comment from iOS

**Comment by verma-manish58** [comment]
comment from iOS
