### ISSUE TITLE
 How to fetch last commit for OCTRepository ?

### ISSUE THREAD

**Issue by HalidCisse** [octokit/octokit.objc#295]
I'm wondering if there is a way to fetch last commit for an OCTRepository

**Comment by mdiep** [comment]
You could use [this API](https://developer.github.com/changes/2016-04-12-commit-reference-sha-api-is-now-official/), but AFAIK it hasn't been added to OctoKit yet.

**Comment by HalidCisse** [comment]
thanks for your response

**Comment by HalidCisse** [comment]
thanks for your response
