### ISSUE TITLE
Build Failed: What should I do ?

### ISSUE THREAD

**Issue by shenAlexy** [octokit/octokit.objc#296]
clang: error: no such file or directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/CarrierBundleUtilities.tbd'

clang: error: no such file or directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/gcrt1.o'

clang: error: no such file or directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/IOABPLib.tbd'

**Comment by mdiep** [comment]
That looks like a problem with the simulator. You may want to download a new copy of it and/or Xcode.

**Comment by shenAlexy** [comment]
But I use Xcode 7.3 and iOS 9.3 simulator. I solved the first and the last problem,"Link Binary With Libraries", frameWork Optional.But the second problem don't be solved in this way!

**Comment by mdiep** [comment]
It looks like your copy of the simulator may be corrupt.

**Comment by shenAlexy** [comment]
The last I use Carthage to build.
