### ISSUE TITLE
Sign in Success,but authenticatedClient.user info incomplete.

### ISSUE THREAD

**Issue by shenAlexy** [octokit/octokit.objc#297]
I try to sign in through the app with these code:

`[OCTClient setClientID:kClientID clientSecret:kClient_Secret];

```
OCTUser *user = [OCTUser userWithRawLogin:self.loginView.userNameTextField.text server:OCTServer.dotComServer];
@weakify(self)
[[[OCTClient signInAsUser:user password:self.loginView.passwordTextField.text oneTimePassword:nil scopes:OCTClientAuthorizationScopesUser note:nil noteURL:nil fingerprint:nil] deliverOn:RACScheduler.mainThreadScheduler] subscribeNext:^(OCTClient *authenticatedClient) {
     // Authentication was successful. Do something with the created client.

    //Store the SSKeychain info
    SSKeychain.rawLogin = authenticatedClient.user.rawLogin;
    SSKeychain.password = self.loginView.passwordTextField.text;
    SSKeychain.token = authenticatedClient.token;

    @strongify(self)
    [self LoginButton:self.loginView.loginBtn success:YES];

 } error:^(NSError *error) {}`
```

I insert the breakPoint for this ,and I got these information：

`po authenticatedClient.user
<OCTUser: 0x7fc840e35f80> {
    HTMLURL = "<null>";
    avatarURL = "<null>";
    bio = "<null>";
    blog = "<null>";
    collaborators = 0;
    company = "<null>";
    diskUsage = 0;
    email = "<null>";
    followers = 0;
    following = 0;
    location = "<null>";
    login = "<null>";
    name = "<null>";
    objectID = "<null>";
    plan = "<null>";
    privateGistCount = 0;
    privateRepoCount = 0;
    publicGistCount = 0;
    publicRepoCount = 0;
    rawLogin = shenAlexy;
    repositories = "<null>";
    server = "<OCTServer: 0x7fc840e35980> {\n    baseURL = \"<null>\";\n}";
}`

Why these message is not complete? What' wrong with me? help....thanks a lot!

**Comment by shenAlexy** [comment]
who can help me?

**Comment by iusn** [comment]
me too!!

**Comment by DarielChen** [comment]
me too!!!

**Comment by rjk40** [comment]
I as well

**Comment by DarielChen** [comment]
https://github.com/leichunfeng/octokit.objc/tree/54474a6947342ddedb4f3dc37ca6e54c050d92bf

**Comment by leichunfeng** [comment]
Related to #244

**Comment by rjk40** [comment]
What do you mean ? Sorry the users info is missing
