### ISSUE TITLE
Sign in using safari view controller API

### ISSUE THREAD

**Issue by HalidCisse** [octokit/octokit.objc#302]
By using `signInToServerUsingWebBrowser` and targeting IOS 9 i got this from apple : 

> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience. 
> 
> Please revise your app to enable users to sign in or register for an account in the app. 
> 
> We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

**Comment by joshaber** [comment]
Yeah, Octokit.objc predates the Safari view controller. I'd welcome a PR adding support.
