### ISSUE TITLE
Login succeed but token is always empty

### ISSUE THREAD

**Issue by GorelH** [octokit/octokit.objc#303]
```
OCTUser *user = [OCTUser userWithRawLogin:_nameLabel.text server:OCTServer.dotComServer]; 
[[[OCTClient signInAsUser:user password:_passLabel.text oneTimePassword:nil scopes: OCTClientAuthorizationScopesUser | OCTClientAuthorizationScopesRepository note:nil noteURL:nil fingerprint:nil]
 deliverOn:RACScheduler.mainThreadScheduler]
 subscribeNext:^(OCTClient *client) {         
     BOOL isAuthenticated = [client isAuthenticated];  // true but token is always @""       
 } error:^(NSError *error) {
 }];
```

And if i tried a request i got 401
Any help is greatly appreciated

**Comment by HalidCisse** [comment]
Resolved when i reseted all tokens from GitHub App.

**Comment by HalidCisse** [comment]
Try reseting all oauth tokens from GitHub app.

**Comment by iusn** [comment]
me too I wirte like his:

    `OCTUser *user = [OCTUser userWithRawLogin:@"username" server:OCTServer.dotComServer];
    [[OCTClient
      signInAsUser:user password:@"password" oneTimePassword:nil scopes:OCTClientAuthorizationScopesUser|OCTClientAuthorizationScopesRepository]
     subscribeNext:^(OCTClient *authenticatedClient) {
//         NSLog(@">>>>>>>>>%@",authenticatedClient);
         
         OCTUser *currentUser  = authenticatedClient.user;
         
         NSLog(@"name%@",currentUser.name);
        
         NSLog(@"repositories >>>>%ld",[currentUser.repositories count]);
         
         NSLog(@"email>>>>>>>>%@",currentUser.email);
        
     } error:^(NSError *error) {
         NSLog(@">>>>>>>>>>%@",error);
         // Authentication failed.
     }];`

why name always nil?
who can help me, Thank you!
