### ISSUE TITLE
Is it possible to delete a gist?

### ISSUE THREAD

**Issue by hkalexling** [octokit/octokit.objc#307]
[OCTClient+Gists](https://github.com/octokit/octokit.objc/blob/master/OctoKit/OCTClient%2BGists.h) provides functions to fetch, create and modify gists, but I did't see a way to delete a gist. Did I miss something or is it provided in somewhere else? I did find method to delete gist in [OctoKit.rb](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/gists.rb) so I think it's achievable. 

Any help would be appreciated.

**Comment by joshaber** [comment]
Yes, the GitHub.com API exists but Octokit.objc doesn't expose it. A pull request would be great 😄

**Comment by hkalexling** [comment]
Sure, pull request sent :)
