### ISSUE TITLE
Error Domain=OCTClientErrorDomain Code=666 "Sign In Required"

### ISSUE THREAD

**Issue by jienice** [octokit/octokit.objc#312]
login code

`
    
    void(^doNext)(OCTClient *authenticatedClient) = ^(OCTClient *authenticatedClient){
        
        [SAMKeychain mg_setAccessToken:authenticatedClient.token];
        [SAMKeychain mg_setPassWord:self.passWord];
        [SAMKeychain mg_setRawlogin:authenticatedClient.user.rawLogin];
        [MGSharedDelegate setClient:authenticatedClient];
    };
    
    self.loginCommand = [[RACCommand alloc]initWithSignalBlock:^RACSignal *(NSString *oneTimePassword) {
        @strongify(self);
        OCTUser *user = [OCTUser userWithRawLogin:self.userName server:OCTServer.dotComServer];
        return [[OCTClient signInAsUser:user
                               password:self.passWord
                        oneTimePassword:oneTimePassword
                                 scopes:OCTClientAuthorizationScopesRepository]
                doNext:doNext];
    }];
    
`
`Error Domain=OCTClientErrorDomain Code=666 "Sign In Required" UserInfo={NSUnderlyingError=0x60800005f740 {Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299,304), got 401" UserInfo={NSLocalizedRecoverySuggestion={"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}, NSErrorFailingURLKey=https://api.github.com/authorizations/clients/e44fe151f15da8da1e3c, AFNetworkingOperationFailingURLRequestErrorKey=<NSMutableURLRequest: 0x618000010470> { URL: https://api.github.com/authorizations/clients/e44fe151f15da8da1e3c }, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x618000226480> { URL: https://api.github.com/authorizations/clients/e44fe151f15da8da1e3c } { status code: 401, headers {
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval";
    "Content-Length" = 83;
    "Content-Security-Policy" = "default-src 'none'";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 20 Feb 2017 02:52:00 GMT";
    Server = "GitHub.com";
    Status = "401 Unauthorized";
    "Strict-Transport-Security" = "max-age=31536000; includeSubdomains; preload";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = deny;
    "X-GitHub-Media-Type" = "github.v3; format=json";
    "X-GitHub-Request-Id" = "C155:76EE:9BF83EB:C3C0D15:58AA59CE";
    "X-RateLimit-Limit" = 60;
    "X-RateLimit-Remaining" = 59;
    "X-RateLimit-Reset" = 1487562720;
    "X-XSS-Protection" = "1; mode=block";
} }, NSLocalizedDescription=Expected status code in (200-299,304), got 401}}, NSLocalizedDescription=Sign In Required, OCTClientErrorHTTPStatusCodeKey=401, OCTClientErrorRequestURLKey=https://api.github.com/authorizations/clients/e44fe151f15da8da1e3c, NSLocalizedFailureReason=You must sign in to access user information.}`

after this error,i gone to revoken users token, but this error  still there.

**Comment by id304m** [comment]
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api"
}
