### ISSUE TITLE
How to access private repo's issue webpage through the access token?

### ISSUE THREAD

**Issue by leichunfeng** [octokit/octokit.objc#314]
[https://github.com/leichunfeng/Prototype/issues/3](https://github.com/leichunfeng/Prototype/issues/3)

![image](https://user-images.githubusercontent.com/5253662/27365870-214be738-5675-11e7-9c27-08ce557740c8.png)

**Comment by joshaber** [comment]
There's currently no way to do this. API tokens are distinct from the user logging in to the site.
