### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ElDragonRojo** [octokit/octokit.objc#89]
I am generally curious about the functionality and workings of OctoKit and would like to learn more and get a feel for it before committing myself to using it.

Is there documentation somewhere? The wiki seems to not exist, and I couldn't find anything in a quick peek through the repo, nor is there a link from the read me.

If not, please consider this a request to create some, or maybe point to a good resource elsewhere online.

**Comment by istx25** [comment]
It would be great if we could move/make a copy of the documentation somewhere else (a website, wiki, pdf, something)
